version: '3'

services:
  php:
    build:
      context: .
    container_name: php
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=adoorei
      - MYSQL_DATABASE=adoorei
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
